<a href="https://colab.research.google.com/github/YPTusar/Machine-Learning-Lab/blob/main/Stroke_Prediction_with_classification_algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Project 2: Exploring different types of Classification Algorithms**

ETE-456

*Fuzzy and Neural Networks Sessional*

*ID : 1608013*

**Objective:**

Apply various classification algorithms on a real world dataset.

Import the Dataset




In [ ]:
!wget -O stroke-data.csv https://www.dropbox.com/s/zgburk3yces5tee/healthcare-dataset-stroke-data.csv?dl=0

In [ ]:
import numpy as np        
import pandas as pd     
import matplotlib.pyplot as plt       
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
dataset = pd.read_csv('stroke-data.csv')
dataset

id  gender   age  ...   bmi   smoking_status stroke
0      9046    Male  67.0  ...  36.6  formerly smoked      1
1     51676  Female  61.0  ...   NaN     never smoked      1
2     31112    Male  80.0  ...  32.5     never smoked      1
3     60182  Female  49.0  ...  34.4           smokes      1
4      1665  Female  79.0  ...  24.0     never smoked      1
...     ...     ...   ...  ...   ...              ...    ...
5105  18234  Female  80.0  ...   NaN     never smoked      0
5106  44873  Female  81.0  ...  40.0     never smoked      0
5107  19723  Female  35.0  ...  30.6     never smoked      0
5108  37544    Male  51.0  ...  25.6  formerly smoked      0
5109  44679  Female  44.0  ...  26.2          Unknown      0

[5110 rows x 12 columns]

In [ ]:
dataset.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [ ]:
dataset.isnull().value_counts() #bmi contains null value

id     gender  age    hypertension  heart_disease  ever_married  work_type  Residence_type  avg_glucose_level  bmi    smoking_status  stroke
False  False   False  False         False          False         False      False           False              False  False           False     4909
                                                                                                               True   False           False      201
dtype: int64

In [ ]:
dataset['bmi'].isnull().value_counts() #bmi contains 201 null value

False    4909
True      201
Name: bmi, dtype: int64

Filling the null value with average value

In [ ]:
mean_value=dataset.mean()

In [ ]:
mean_value=dataset['bmi'].mean()
dataset['bmi'].fillna(value=mean_value, inplace=True)
dataset

id  gender   age  ...        bmi   smoking_status stroke
0      9046    Male  67.0  ...  36.600000  formerly smoked      1
1     51676  Female  61.0  ...  28.893237     never smoked      1
2     31112    Male  80.0  ...  32.500000     never smoked      1
3     60182  Female  49.0  ...  34.400000           smokes      1
4      1665  Female  79.0  ...  24.000000     never smoked      1
...     ...     ...   ...  ...        ...              ...    ...
5105  18234  Female  80.0  ...  28.893237     never smoked      0
5106  44873  Female  81.0  ...  40.000000     never smoked      0
5107  19723  Female  35.0  ...  30.600000     never smoked      0
5108  37544    Male  51.0  ...  25.600000  formerly smoked      0
5109  44679  Female  44.0  ...  26.200000          Unknown      0

[5110 rows x 12 columns]

In [ ]:
dataset.isnull().value_counts() 

id     gender  age    hypertension  heart_disease  ever_married  work_type  Residence_type  avg_glucose_level  bmi    smoking_status  stroke
False  False   False  False         False          False         False      False           False              False  False           False     5110
dtype: int64

In [ ]:
dataset.duplicated().sum()

0

In [ ]:
feature = dataset[['gender','age','hypertension','heart_disease','bmi','smoking_status']]
target = dataset[['stroke']]

In [ ]:
target

stroke
0          1
1          1
2          1
3          1
4          1
...      ...
5105       0
5106       0
5107       0
5108       0
5109       0

[5110 rows x 1 columns]

In [ ]:
feature

gender   age  hypertension  heart_disease        bmi   smoking_status
0       Male  67.0             0              1  36.600000  formerly smoked
1     Female  61.0             0              0  28.893237     never smoked
2       Male  80.0             0              1  32.500000     never smoked
3     Female  49.0             0              0  34.400000           smokes
4     Female  79.0             1              0  24.000000     never smoked
...      ...   ...           ...            ...        ...              ...
5105  Female  80.0             1              0  28.893237     never smoked
5106  Female  81.0             0              0  40.000000     never smoked
5107  Female  35.0             0              0  30.600000     never smoked
5108    Male  51.0             0              0  25.600000  formerly smoked
5109  Female  44.0             0              0  26.200000          Unknown

[5110 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_f = LabelEncoder()
feature['gender'] = labelencoder_f.fit_transform(feature['gender'])
feature['smoking_status'] = labelencoder_f.fit_transform(feature['smoking_status'])

In [ ]:
feature['gender']

0       1
1       0
2       1
3       0
4       0
       ..
5105    0
5106    0
5107    0
5108    1
5109    0
Name: gender, Length: 5110, dtype: int64

In [ ]:
feature['smoking_status']

0       1
1       2
2       2
3       3
4       2
       ..
5105    2
5106    2
5107    2
5108    1
5109    0
Name: smoking_status, Length: 5110, dtype: int64

In [ ]:
feature

gender   age  hypertension  heart_disease        bmi  smoking_status
0          1  67.0             0              1  36.600000               1
1          0  61.0             0              0  28.893237               2
2          1  80.0             0              1  32.500000               2
3          0  49.0             0              0  34.400000               3
4          0  79.0             1              0  24.000000               2
...      ...   ...           ...            ...        ...             ...
5105       0  80.0             1              0  28.893237               2
5106       0  81.0             0              0  40.000000               2
5107       0  35.0             0              0  30.600000               2
5108       1  51.0             0              0  25.600000               1
5109       0  44.0             0              0  26.200000               0

[5110 rows x 6 columns]

Splliting the dataset

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(feature,target,test_size = 0.15,random_state = 0)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(4343, 6)
(767, 6)


Feature scalling

In [ ]:
X_sc = StandardScaler()
X_train = X_sc.fit_transform(X_train)
X_test = X_sc.transform(X_test)

Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
# Fitting Logistic Regression to the training dataset
lr = LogisticRegression()
lr.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
y_pred = lr.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,f1_score,precision_score,recall_score
confusion_matrix(y_test,y_pred)

array([[726,   0],
       [ 41,   0]])

In [ ]:
print(classification_report(y_test,y_pred,target_names = ['No','Yes']))

              precision    recall  f1-score   support

          No       0.95      1.00      0.97       726
         Yes       0.00      0.00      0.00        41

    accuracy                           0.95       767
   macro avg       0.47      0.50      0.49       767
weighted avg       0.90      0.95      0.92       767



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


KNN Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
# Classifier Model
classifier = KNeighborsClassifier(n_neighbors=5, metric = 'minkowski', p=2)
classifier.fit(X_train,y_train)
# Prediction
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [ ]:
# Making confusing matrix
print(confusion_matrix(y_test,y_pred))
# Making confusing matrix
# it is used to check the accuracy of the classification
print(classification_report(y_test,y_pred,target_names = ['No','Yes']))

[[721   5]
 [ 38   3]]
              precision    recall  f1-score   support

          No       0.95      0.99      0.97       726
         Yes       0.38      0.07      0.12        41

    accuracy                           0.94       767
   macro avg       0.66      0.53      0.55       767
weighted avg       0.92      0.94      0.93       767



SVM

In [ ]:
from sklearn.svm import SVC
# Classifier Model
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train,y_train)
# Prediction
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# Making confusing matrix
print(confusion_matrix(y_test,y_pred))
# Making confusing matrix
# it is used to check the accuracy of the classification
print(classification_report(y_test,y_pred,target_names = ['No','Yes']))

[[726   0]
 [ 41   0]]
              precision    recall  f1-score   support

          No       0.95      1.00      0.97       726
         Yes       0.00      0.00      0.00        41

    accuracy                           0.95       767
   macro avg       0.47      0.50      0.49       767
weighted avg       0.90      0.95      0.92       767



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
# Classifier Model
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train,y_train)
# Prediction
y_pred = classifier.predict(X_test)

In [ ]:
# Making confusing matrix
print(confusion_matrix(y_test,y_pred))
# Making confusing matrix
# it is used to check the accuracy of the classification
print(classification_report(y_test,y_pred,target_names = ['No','Yes']))

[[695  31]
 [ 38   3]]
              precision    recall  f1-score   support

          No       0.95      0.96      0.95       726
         Yes       0.09      0.07      0.08        41

    accuracy                           0.91       767
   macro avg       0.52      0.52      0.52       767
weighted avg       0.90      0.91      0.91       767



Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
# Classifier Model
classifier = RandomForestClassifier(n_estimators=10, criterion ='entropy', random_state = 0)
classifier.fit(X_train,y_train)
# Prediction
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [ ]:
# Making confusing matrix
print(confusion_matrix(y_test,y_pred))
# Making confusing matrix
# it is used to check the accuracy of the classification
print(classification_report(y_test,y_pred,target_names = ['No','Yes']))

[[722   4]
 [ 41   0]]
              precision    recall  f1-score   support

          No       0.95      0.99      0.97       726
         Yes       0.00      0.00      0.00        41

    accuracy                           0.94       767
   macro avg       0.47      0.50      0.48       767
weighted avg       0.90      0.94      0.92       767



Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
# Classifier Model
classifier = GaussianNB()
classifier.fit(X_train,y_train)
# Prediction
y_pred = classifier.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# Making confusing matrix
print(confusion_matrix(y_test,y_pred))
# Making confusing matrix
# it is used to check the accuracy of the classification
print(classification_report(y_test,y_pred,target_names = ['No','Yes']))

[[666  60]
 [ 30  11]]
              precision    recall  f1-score   support

          No       0.96      0.92      0.94       726
         Yes       0.15      0.27      0.20        41

    accuracy                           0.88       767
   macro avg       0.56      0.59      0.57       767
weighted avg       0.91      0.88      0.90       767

